using System.Text.Json;
using System.Text.Json.Serialization;

namespace MiLsp.Worker;

public sealed class GraphObservationBatch
{
    [JsonPropertyName("schema_version")] public int SchemaVersion { get; set; } = 1;
    [JsonPropertyName("workspace_identity")] public string WorkspaceIdentity { get; set; } = "";
    [JsonPropertyName("repository_identity")] public string RepositoryIdentity { get; set; } = "";
    [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn";
    [JsonPropertyName("backend_version")] public string BackendVersion { get; set; } = "";
    [JsonPropertyName("extractor_version")] public string ExtractorVersion { get; set; } = "";
    [JsonPropertyName("project_or_module")] public string ProjectOrModule { get; set; } = "";
    [JsonPropertyName("source_fingerprint")] public string SourceFingerprint { get; set; } = new('0', 64);
    [JsonPropertyName("config_fingerprint")] public string ConfigFingerprint { get; set; } = new('0', 64);
    [JsonPropertyName("completeness")] public string Completeness { get; set; } = "complete";
    [JsonPropertyName("capabilities")] public List<GraphObservationCapability> Capabilities { get; set; } = [];
    [JsonPropertyName("coverage")] public List<GraphObservationCoverage> Coverage { get; set; } = [];
    [JsonPropertyName("nodes")] public List<GraphObservationNode> Nodes { get; set; } = [];
    [JsonPropertyName("edges")] public List<GraphObservationEdge> Edges { get; set; } = [];
    [JsonPropertyName("evidence")] public List<GraphObservationEvidence> Evidence { get; set; } = [];
    [JsonPropertyName("unresolved")] public List<GraphObservationUnresolved> Unresolved { get; set; } = [];
    [JsonPropertyName("omissions")] public List<GraphObservationOmission> Omissions { get; set; } = [];
    [JsonPropertyName("resource_stats"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public GraphObservationResourceStats? ResourceStats { get; set; }
    [JsonPropertyName("digest")] public string Digest { get; set; } = new('0', 64);
}
public sealed class GraphObservationNode { [JsonPropertyName("ref")] public string Ref { get; set; } = ""; [JsonPropertyName("key")] public GraphNodeKey Key { get; set; } = new(); [JsonPropertyName("display_name")] public string DisplayName { get; set; } = ""; [JsonPropertyName("source_digest")] public string SourceDigest { get; set; } = new('0',64); [JsonPropertyName("claim_status")] public string ClaimStatus { get; set; } = "exact"; [JsonPropertyName("resolution")] public string Resolution { get; set; } = "roslyn"; }
public sealed class GraphNodeKey { [JsonPropertyName("repository_identity")] public string RepositoryIdentity { get; set; } = ""; [JsonPropertyName("backend_type")] public string BackendType { get; set; } = "roslyn"; [JsonPropertyName("language")] public string Language { get; set; } = "csharp"; [JsonPropertyName("project_or_module")] public string ProjectOrModule { get; set; } = ""; [JsonPropertyName("owner_path")] public string OwnerPath { get; set; } = ""; [JsonPropertyName("symbol_kind")] public string SymbolKind { get; set; } = ""; [JsonPropertyName("semantic_identity")] public string SemanticIdentity { get; set; } = ""; }
public sealed class GraphObservationEdge { [JsonPropertyName("ref")] public string Ref { get; set; } = ""; [JsonPropertyName("from_ref")] public string FromRef { get; set; } = ""; [JsonPropertyName("to_ref")] public string ToRef { get; set; } = ""; [JsonPropertyName("relation")] public string Relation { get; set; } = ""; [JsonPropertyName("scope")] public string Scope { get; set; } = "symbol"; [JsonPropertyName("status")] public string Status { get; set; } = "exact"; [JsonPropertyName("owner_path")] public string OwnerPath { get; set; } = ""; [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn"; [JsonPropertyName("resolution")] public string Resolution { get; set; } = "roslyn"; [JsonPropertyName("source_digest")] public string SourceDigest { get; set; } = new('0',64); }
public sealed class GraphObservationEvidence { [JsonPropertyName("ref")] public string Ref { get; set; } = ""; [JsonPropertyName("node_ref"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? NodeRef { get; set; } [JsonPropertyName("edge_ref"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? EdgeRef { get; set; } [JsonPropertyName("source_uri")] public string SourceUri { get; set; } = ""; [JsonPropertyName("range"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public GraphObservationRange? Range { get; set; } [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn"; [JsonPropertyName("extractor_version")] public string ExtractorVersion { get; set; } = ""; [JsonPropertyName("source_digest")] public string SourceDigest { get; set; } = new('0',64); [JsonPropertyName("observed_digest")] public string ObservedDigest { get; set; } = new('0',64); [JsonPropertyName("claim_kind")] public string ClaimKind { get; set; } = "declaration"; [JsonPropertyName("status")] public string Status { get; set; } = "exact"; }
public sealed class GraphObservationRange { [JsonPropertyName("start_line")] public int StartLine { get; set; } [JsonPropertyName("start_column")] public int StartColumn { get; set; } [JsonPropertyName("end_line")] public int EndLine { get; set; } [JsonPropertyName("end_column")] public int EndColumn { get; set; } }
public sealed class GraphObservationUnresolved { [JsonPropertyName("ref")] public string Ref { get; set; } = ""; [JsonPropertyName("owner_path")] public string OwnerPath { get; set; } = ""; [JsonPropertyName("subject_kind")] public string SubjectKind { get; set; } = "symbol"; [JsonPropertyName("capability")] public string Capability { get; set; } = ""; [JsonPropertyName("selector_digest")] public string SelectorDigest { get; set; } = new('0',64); [JsonPropertyName("reason_code")] public string ReasonCode { get; set; } = "ambiguous"; [JsonPropertyName("candidates")] public List<string> Candidates { get; set; } = []; [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn"; [JsonPropertyName("source_digest"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? SourceDigest { get; set; } [JsonPropertyName("recovery_hint_code")] public string RecoveryHintCode { get; set; } = "inspect"; }
public sealed class GraphObservationOmission { [JsonPropertyName("ref")] public string Ref { get; set; } = ""; [JsonPropertyName("owner_path")] public string OwnerPath { get; set; } = ""; [JsonPropertyName("subject_kind")] public string SubjectKind { get; set; } = "file"; [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn"; [JsonPropertyName("capability")] public string Capability { get; set; } = ""; [JsonPropertyName("reason_code")] public string ReasonCode { get; set; } = "compiler_partial"; [JsonPropertyName("recovery_hint_code")] public string RecoveryHintCode { get; set; } = "retry"; }
public sealed class GraphObservationCapability { [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn"; [JsonPropertyName("capability")] public string Capability { get; set; } = ""; [JsonPropertyName("state")] public string State { get; set; } = "stable"; }
public sealed class GraphObservationCoverage { [JsonPropertyName("backend")] public string Backend { get; set; } = "roslyn"; [JsonPropertyName("capability")] public string Capability { get; set; } = ""; [JsonPropertyName("eligible")] public int Eligible { get; set; } [JsonPropertyName("observed")] public int Observed { get; set; } [JsonPropertyName("unresolved")] public int Unresolved { get; set; } [JsonPropertyName("omitted")] public int Omitted { get; set; } }
public sealed class GraphObservationResourceStats { [JsonPropertyName("elapsed_ms")] public long ElapsedMilliseconds { get; set; } [JsonPropertyName("rss_bytes")] public long RssBytes { get; set; } }
